apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secret
  namespace: url-shortener
type: Opaque
data:
  # These are empty placeholders - in a real scenario, you'd add actual secrets
  # Base64 encoded values: echo -n "your-value" | base64
  REDIS_PASSWORD: ""  # We're not using password auth in this example